version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: zenon-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zenon_bank
    ports:
      - "3308:3306"